name: crongeneratesteamdepotmapping

on:
  schedule:
    - cron: '0 17 * * 5' # Runs every Friday at 5pm UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  generate_version_number:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ github.ref == 'refs/heads/master' && steps.buildnumber.outputs.build_number || 1 }}
    steps:
    - name: Generate build number
      if: github.ref == 'refs/heads/master'
      id: buildnumber
      uses: onyxmueller/build-tag-number@v1
      with:
        token: ${{secrets.github_token}}

  generate_and_publish_new_appdepotmapping:
    needs: generate_version_number
    runs-on: ubuntu-latest
    steps:
    - name: Create output directory
      run: mkdir -p ${{ github.workspace }}/output
    - name: Run Docker
      run: |
        export VERSION=1.0.${{needs.generate_version_number.outputs.build_number}}
        echo Version: $VERSION
        STEAMTOKEN=$(echo '${{ secrets.STEAMTOKEN }}' | jq -c .)
        docker run --rm -v ${{ github.workspace }}/output:/app/output -e STEAMTOKEN="$STEAMTOKEN" devedse/develancacheui_steamdepotfinderconsoleapp
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: 1.0.${{needs.generate_version_number.outputs.build_number}}
        files: ./output/app-depot-output-cleaned.csv
